data_dir: I:/Evo_PRISM/bulk_rna_data/Kallisto_v1/results_kallisto
results_dir: I:/Evo_PRISM/benchmark/results/snakemake
samples:
- ctrl_1_Hair_germ
- ctrl_1_lower_bulge
- ctrl_1_upper_bulge
- ctrl_2_Hair_germ
- ctrl_2_lower_bulge
- ctrl_2_upper_bulge
- ctrl_3_Hair_germ
- ctrl_3_lower_bulge
- ctrl_3_upper_bulge
- ctrl_4_Hair_germ
- ctrl_4_lower_bulge
- ctrl_4_upper_bulge
- pw120hr_1_Hair_germ
- pw120hr_1_Hair_germ_a6
- pw120hr_1_upper_bulge
- pw120hr_2_Hair_germ
- pw120hr_2_Hair_germ_a6
- pw120hr_2_lower_bulge
- pw120hr_2_upper_bulge
- pw120hr_3_Hair_germ
- pw120hr_3_lower_bulge
- pw120hr_3_upper_bulge
- pw120hr_4_Hair_germ
- pw120hr_4_Hair_germ_a6
- pw120hr_4_lower_bulge
- pw120hr_4_upper_bulge
- pw12hr_1_Hair_germ
- pw12hr_1_lower_bulge
- pw12hr_1_upper_bulge
- pw12hr_2_Hair_germ
- pw12hr_2_lower_bulge
- pw12hr_2_upper_bulge
- pw12hr_3_Hair_germ
- pw12hr_3_lower_bulge
- pw12hr_3_upper_bulge
- pw12hr_4_Hair_germ
- pw12hr_4_lower_bulge
- pw12hr_4_upper_bulge
- pw24hr_1_Hair_germ
- pw24hr_1_lower_bulge
- pw24hr_1_upper_bulge
- pw24hr_2_Hair_germ
- pw24hr_2_lower_bulge
- pw24hr_2_upper_bulge
- pw24hr_3_Hair_germ
- pw24hr_3_lower_bulge
- pw24hr_3_upper_bulge
- pw24hr_4_Hair_germ
- pw24hr_4_lower_bulge
- pw24hr_4_upper_bulge
- pw36hr_1_Hair_germ
- pw36hr_1_lower_bulge
- pw36hr_1_upper_bulge
- pw36hr_2_Hair_germ
- pw36hr_2_lower_bulge
- pw36hr_2_upper_bulge
- pw36hr_3_Hair_germ
- pw36hr_3_lower_bulge
- pw36hr_3_upper_bulge
- pw36hr_4_Hair_germ
- pw36hr_4_lower_bulge
- pw36hr_4_upper_bulge
- pw48hr_1_Hair_germ
- pw48hr_1_lower_bulge
- pw48hr_1_upper_bulge
- pw48hr_2_Hair_germ
- pw48hr_2_lower_bulge
- pw48hr_2_upper_bulge
- pw48hr_3_Hair_germ
- pw48hr_3_lower_bulge
- pw48hr_3_upper_bulge
- pw48hr_4_Hair_germ
- pw48hr_4_lower_bulge
- pw48hr_4_upper_bulge
- pw6hr_1_Hair_germ
- pw6hr_1_lower_bulge
- pw6hr_1_upper_bulge
- pw6hr_2_Hair_germ
- pw6hr_2_lower_bulge
- pw6hr_2_upper_bulge
- pw6hr_3_Hair_germ
- pw6hr_3_lower_bulge
- pw6hr_3_upper_bulge
- pw6hr_4_Hair_germ
- pw6hr_4_lower_bulge
- pw6hr_4_upper_bulge
- pw72hr_1_Hair_germ
- pw72hr_1_lower_bulge
- pw72hr_1_upper_bulge
- pw72hr_2_Hair_germ
- pw72hr_2_lower_bulge
- pw72hr_2_upper_bulge
- pw72hr_3_Hair_germ
- pw72hr_3_lower_bulge
- pw72hr_3_upper_bulge
- pw72hr_4_Hair_germ
- pw72hr_4_lower_bulge
- pw72hr_4_upper_bulge
