"""
Generate a crisp, publication-quality, perfectly readable vector architecture diagram
for Evo_PRISM using matplotlib.
This guarantees 100% legible English text and sharp, academic-grade layout,
completely avoiding the garbled/illegible text generated by AI diffusion models.
"""

from __future__ import annotations

import matplotlib.pyplot as plt
import matplotlib.patches as patches
from pathlib import Path

# Setup paths
ROOT = Path(__file__).parent.parent
OUTPUT_PATH = ROOT / "docs" / "images" / "Figure1_System_Architecture_v2.png"
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

# Colors
COLORS = {
    "bg": "#ffffff",
    "gateway": "#fff3e0",      # Light orange
    "gateway_border": "#ef6c00",
    "lake": "#eceff1",         # Gray-blue
    "lake_border": "#37474f",
    "agent": "#e3f2fd",        # Light blue
    "agent_border": "#1565c0",
    "hit": "#e8f5e9",          # Light green
    "hit_border": "#2e7d32",
    "text": "#1a1a1a",
    "helix_bg": "#fff9c4",     # Soft yellow for HELIX subgraph
    "helix_border": "#fbc02d",
    "engram_bg": "#f3e5f5",    # Soft purple for ENGRAM subgraph
    "engram_border": "#7b1fa2",
    "arrow": "#455a64"
}

def draw_diagram():
    fig, ax = plt.subplots(figsize=(11, 9.5), dpi=300)
    ax.set_xlim(0, 11)
    ax.set_ylim(0, 10.5)
    ax.axis("off")
    fig.patch.set_facecolor(COLORS["bg"])
    
    # 1. Draw Subgraphs (HELIX and ENGRAM)
    # HELIX Group (right/center area)
    helix_box = patches.FancyBboxPatch(
        (5.1, 3.6), 5.4, 4.2,
        boxstyle="round,pad=0.2",
        facecolor="#f9fbe7",
        edgecolor=COLORS["helix_border"],
        linewidth=1.5,
        linestyle="--",
        zorder=1
    )
    ax.add_patch(helix_box)
    ax.text(10.3, 7.6, "HELIX: Self-Evolving Tool Evolution Loop", 
            ha="right", va="bottom", fontsize=10.5, color=COLORS["helix_border"], fontweight="bold", fontstyle="italic")
    
    # ENGRAM Group (bottom area)
    engram_box = patches.FancyBboxPatch(
        (0.5, 0.6), 10.0, 2.3,
        boxstyle="round,pad=0.2",
        facecolor="#f3e5f5",
        edgecolor=COLORS["engram_border"],
        linewidth=1.5,
        linestyle="-.",
        zorder=1
    )
    ax.add_patch(engram_box)
    ax.text(10.3, 2.7, "ENGRAM: Semantic Memory Lakehouse", 
            ha="right", va="bottom", fontsize=10.5, color=COLORS["engram_border"], fontweight="bold", fontstyle="italic")
    
    # 2. Draw Nodes
    # Helper function for drawing readable boxes
    def draw_node(x, y, w, h, text, style_key, shape="rect"):
        bg_col = COLORS[style_key]
        border_col = COLORS[style_key + "_border"]
        if shape == "rect":
            p = patches.FancyBboxPatch(
                (x - w/2, y - h/2), w, h,
                boxstyle="round,pad=0.1",
                facecolor=bg_col,
                edgecolor=border_col,
                linewidth=1.8,
                zorder=3
            )
        elif shape == "ellipse":
            p = patches.Ellipse(
                (x, y), w, h,
                facecolor=bg_col,
                edgecolor=border_col,
                linewidth=1.8,
                zorder=3
            )
        ax.add_patch(p)
        ax.text(x, y, text, ha="center", va="center", fontsize=8.5, color=COLORS["text"], fontweight="semibold", zorder=4)
        return (x, y, w, h)

    # Top Node
    draw_node(5.5, 10.0, 3.2, 0.6, "User Query /\nNatural Language Request", "gateway", "ellipse")
    
    # Gateway Node
    draw_node(5.5, 8.8, 3.6, 0.7, "Adaptive De-duplication &\nRouting Gateway", "gateway")
    
    # L1 Cache Routing Decisions
    draw_node(2.5, 7.3, 2.2, 0.7, "L1 Gold Cache Hit\n(Sub-second Response)", "hit")
    draw_node(5.5, 7.3, 2.4, 0.7, "L2 Silver Cache Hit\n(Fast SQL/MCP Exec)", "hit")
    
    # Agent Brain
    draw_node(8.5, 7.0, 2.0, 0.6, "Evo_PRISM\nLLM Agent Brain", "agent")
    
    # HELIX Components
    draw_node(8.5, 5.6, 2.2, 0.6, "LLM Ad-hoc\nCode Generation", "agent")
    draw_node(8.5, 4.3, 2.2, 0.6, "Secure Sandbox\nIsolated Execution", "agent")
    draw_node(5.8, 4.3, 2.0, 0.6, "L2 Active\nMCP Toolset", "hit")
    
    # ENGRAM Components (L1, L2, L3)
    draw_node(2.5, 1.6, 2.2, 0.8, "L1 Gold Cache Storage\n(hermes_cache.duckdb)\nTTL 7 Days & Auto Inval", "lake")
    draw_node(5.5, 1.6, 2.4, 0.8, "L2 Silver Feature Store\n(sample_registry &\nanalysis_history)", "lake")
    draw_node(8.5, 1.6, 2.4, 0.8, "L3 Bronze Raw Data\n(Read-Only Genomics\ncounts & files)", "lake")
    
    # Final Scientific Output / Return Node
    draw_node(2.5, 5.6, 2.3, 0.8, "Final Scientific Output\n& Deliverables\n(PNG Plots, DEG CSV, H5AD)", "hit")
    
    # 3. Draw Directed Arrows with Labels
    arrow_style = dict(arrowstyle="->", lw=1.5, color=COLORS["arrow"])
    
    # User Query -> Gateway
    ax.annotate("", xy=(5.5, 9.2), xytext=(5.5, 9.6), arrowprops=arrow_style)
    
    # Gateway -> L1 Routing Decisions
    # To L1 Hit
    ax.annotate("", xy=(2.5, 7.7), xytext=(4.2, 8.8), 
                arrowprops=dict(arrowstyle="->", lw=1.5, color=COLORS["arrow"], connectionstyle="angle,angleA=180,angleB=90,rad=10"))
    ax.text(3.0, 8.4, "Cosine >= 0.88", fontsize=7.5, color="#1b5e20", fontweight="bold")
    
    # To L2 Hit
    ax.annotate("", xy=(5.5, 8.0), xytext=(5.5, 8.4), arrowprops=arrow_style)
    ax.text(5.6, 8.2, "Miss / L2 Hit", fontsize=7.5, color=COLORS["arrow"])
    
    # To LLM Agent
    ax.annotate("", xy=(8.5, 7.4), xytext=(6.8, 8.8), 
                arrowprops=dict(arrowstyle="->", lw=1.5, color=COLORS["arrow"], connectionstyle="angle,angleA=0,angleB=90,rad=10"))
    ax.text(7.7, 8.4, "Miss / No Tool", fontsize=7.5, color=COLORS["arrow"])
    
    # L1 Hit -> Read Cache
    ax.annotate("", xy=(2.5, 2.1), xytext=(2.5, 6.9), arrowprops=arrow_style)
    ax.text(2.6, 3.5, "Read Cache (0-Token)", fontsize=7.5, color="#1b5e20", fontweight="bold")
    
    # L2 Hit -> Invoke Tool
    ax.annotate("", xy=(5.5, 2.1), xytext=(5.5, 6.9), arrowprops=arrow_style)
    ax.text(5.6, 3.5, "Invoke MCP / SQL", fontsize=7.5, color=COLORS["arrow"])
    
    # LLM Agent -> Ad-hoc Code
    ax.annotate("", xy=(8.5, 6.0), xytext=(8.5, 6.6), arrowprops=arrow_style)
    
    # Ad-hoc Code -> Sandbox
    ax.annotate("", xy=(8.5, 4.7), xytext=(8.5, 5.2), arrowprops=arrow_style)
    
    # Sandbox -> Load Raw Data (L3)
    ax.annotate("", xy=(8.5, 2.1), xytext=(8.5, 3.9), arrowprops=arrow_style)
    ax.text(8.6, 3.5, "Load L3 Data", fontsize=7.5, color=COLORS["arrow"])
    
    # L3 -> L2 Conversion
    ax.annotate("", xy=(6.8, 1.6), xytext=(7.2, 1.6), arrowprops=arrow_style)
    ax.text(7.0, 1.8, "Structured Parquet", fontsize=7, ha="center", color=COLORS["arrow"])
    
    # L2 -> L1 Backfill
    ax.annotate("", xy=(3.8, 1.6), xytext=(4.2, 1.6), arrowprops=arrow_style)
    ax.text(4.0, 1.8, "Cache Backfill", fontsize=7, ha="center", color=COLORS["arrow"])
    
    # Sandbox -> Active Toolset (Promotion)
    ax.annotate("", xy=(7.0, 4.3), xytext=(7.3, 4.3), arrowprops=arrow_style)
    ax.text(7.2, 4.5, "Reuse >= 3\nPass Pytest", fontsize=7.5, ha="center", color="#2e7d32", fontweight="bold")
    
    # Active Toolset -> Gateway (HOT Reloading to L2)
    ax.annotate("", xy=(5.0, 8.5), xytext=(5.8, 4.7), 
                arrowprops=dict(arrowstyle="->", lw=1.5, color="#2e7d32", linestyle="--", connectionstyle="arc3,rad=-0.1"))
    ax.text(4.7, 5.1, "Autonomic Code\nPromotion to MCP\n(SemVer Hot-reload)", fontsize=7.5, ha="center", color="#2e7d32", fontweight="bold")
    
    # Return Cache Results to User
    ax.annotate("", xy=(2.5, 6.0), xytext=(2.5, 2.1), 
                arrowprops=dict(arrowstyle="->", lw=1.5, color="#2e7d32", connectionstyle="arc3,rad=0.1"))
    
    # Return L1/L2 Results to Return Node
    ax.annotate("", xy=(2.5, 5.2), xytext=(2.5, 2.1), arrowprops=arrow_style)
    
    # Return Final Deliverables to User Query (Closed Loop)
    ax.annotate("", xy=(3.9, 10.0), xytext=(2.5, 6.0), 
                arrowprops=dict(arrowstyle="->", lw=1.6, color="#2e7d32", connectionstyle="arc3,rad=-0.15"))
    ax.text(2.6, 8.4, "Deliver Scientific\nOutput to User", fontsize=8, color="#2e7d32", fontweight="bold", ha="left")
    
    # Title & Caption Box
    title_box = patches.FancyBboxPatch(
        (0.5, 9.3), 3.0, 0.9,
        boxstyle="round,pad=0.1",
        facecolor="#eceff1",
        edgecolor="#b0bec5",
        linewidth=1.2,
        zorder=2
    )
    ax.add_patch(title_box)
    ax.text(2.0, 9.8, "Evo_PRISM Platform", ha="center", va="center", fontsize=11, fontweight="bold", color="#37474f")
    ax.text(2.0, 9.5, "Overall System Architecture\n& Multimodal Data Flow", ha="center", va="center", fontsize=8, color="#546e7a")

    # Legend / Key
    legend_box = patches.FancyBboxPatch(
        (0.5, 4.0), 1.5, 1.2,
        boxstyle="round,pad=0.1",
        facecolor="#ffffff",
        edgecolor="#cfd8dc",
        linewidth=1.0,
        zorder=2
    )
    ax.add_patch(legend_box)
    ax.text(1.25, 5.0, "KEY / LEGEND", ha="center", va="center", fontsize=8, fontweight="bold", color="#546e7a")
    
    # Legend markers
    ax.add_patch(patches.Rectangle((0.6, 4.6), 0.3, 0.15, facecolor=COLORS["gateway"], edgecolor=COLORS["gateway_border"], lw=1))
    ax.text(1.0, 4.67, "Gateway / IO", fontsize=7, color=COLORS["text"])
    
    ax.add_patch(patches.Rectangle((0.6, 4.3), 0.3, 0.15, facecolor=COLORS["agent"], edgecolor=COLORS["agent_border"], lw=1))
    ax.text(1.0, 4.37, "LLM Agent", fontsize=7, color=COLORS["text"])
    
    ax.add_patch(patches.Rectangle((0.6, 4.1), 0.3, 0.15, facecolor=COLORS["lake"], edgecolor=COLORS["lake_border"], lw=1))
    ax.text(1.0, 4.17, "Medallion Lake", fontsize=7, color=COLORS["text"])

    plt.tight_layout()
    plt.savefig(OUTPUT_PATH, dpi=300, facecolor=COLORS["bg"], bbox_inches="tight")
    plt.close()
    print(f"Generated crisp vector architecture plot at: {OUTPUT_PATH}")

if __name__ == "__main__":
    draw_diagram()
